### ISSUE TITLE
SQL Queries for One Column don't work

### ISSUE THREAD

**Issue by bjfultn** [Caltech-IPAC/hiresprv#26]
Example:
```
state = hiresprv.database.Database('prvcookie.txt')
url = state.search(sql="select TARGET from FILES;")
```

**Comment by JohnGood** [comment]
The query was working fine.  It was some subsequent processing that was parsing the returned table;  it wasn't seeing any delimiters and so wasn't sure whether it was really just one column or a failure to parse.  I've fixed it.

**Comment by bjfultn** [comment]
This is fixed.
