### ISSUE TITLE
HIRES_PRV_Service Notebook fails

### ISSUE THREAD

**Issue by GBruceB** [Caltech-IPAC/hiresprv#35]
The cell

search_string = "select * from FILES where TARGET like 'HD185144' and DATE = '20180922';"

url = state.search(sql=search_string)
df = pd.read_html(url, header=0)[0]
df

fails and returns this traceback:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-6cc348cd0baf> in <module>()
      2 
      3 url = state.search(sql=search_string)
----> 4 df = pd.read_html(url, header=0)[0]
      5 df

~/anaconda3/lib/python3.6/site-packages/pandas/io/html.py in read_html(io, match, flavor, header, index_col, skiprows, attrs, parse_dates, tupleize_cols, thousands, encoding, decimal, converters, na_values, keep_default_na, displayed_only)
    985                   decimal=decimal, converters=converters, na_values=na_values,
    986                   keep_default_na=keep_default_na,
--> 987                   displayed_only=displayed_only)

~/anaconda3/lib/python3.6/site-packages/pandas/io/html.py in _parse(flavor, io, match, attrs, encoding, displayed_only, **kwargs)
    813             break
    814     else:
--> 815         raise_with_traceback(retained)
    816 
    817     ret = []

~/anaconda3/lib/python3.6/site-packages/pandas/compat/__init__.py in raise_with_traceback(exc, traceback)
    401         if traceback == Ellipsis:
    402             _, _, traceback = sys.exc_info()
--> 403         raise exc.with_traceback(traceback)
    404 else:
    405     # this version of raise is a syntax error in Python 3

ValueError: No text parsed from document: http://hiresprv.ipac.caltech.edu/cgi-bin/idlDriver/nph-prvState?workspace=prv_20201015_125941_18216&format=html&sql=select%20%2A%20from%20FILES%20where%20TARGET%20like%20%27HD185144%27%20and%20DATE%20%3D%20%2720180922%27%3B

**Comment by bjfultn** [comment]
I believe this is fixed now. @GBruceB can you confirm?

**Comment by bjfultn** [comment]
@GBruceB confirmed he was able to get through both notebooks last night so this must be working now.
