### ISSUE TITLE
Slow logins in the Notebooks

### ISSUE THREAD

**Issue by GBruceB** [Caltech-IPAC/hiresprv#36]
The logons for both notebooks are very slow.

In HIRES_PRV_service,  login with my test account took 15  mins. The login on the Advanced notebooks has been hung for over an hour.  

By contrast, the login on the  KOA web page took a second or so.

**Comment by GBruceB** [comment]
I note that I can now log on quickly if I am on VPN. I wasn't on VPN when I logged on through the KOA web page

**Comment by bjfultn** [comment]
I can not reproduce this issue. Logins happen in 1-2 s for me whether I'm on the VPN or not. @GBruceB can you test this again to see if it was just some temporary network glitch?

**Comment by GBruceB** [comment]
OK now - think it was a network glitch. Will close
