### ISSUE TITLE
System busy message

### ISSUE THREAD

**Issue by GBruceB** [Caltech-IPAC/hiresprv#37]
I was able to log on (through the VPN). Then when started to execute cells in the Notebooks, I sometimes got seem busy messages:

e.g.
from hiresprv.idldriver import Idldriver

idl = Idldriver('prv.cookies')

rtn = idl.run_script("""
deactivate vdaa185144_r20091231.72
deactivate vdaa185144_r20091231.73
deactivate vdaa185144_r20091231.74
deactivate vdaa185144_r20150606.145
deactivate vdaa185144_r20150606.146
deactivate vdaa185144_r20150606.147
rv 185144 r20091231.72
rv 185144 r20091231.73
rv 185144 r20091231.74
rv 185144 r20150606.145
rv 185144 r20150606.146
rv 185144 r20150606.147
rvcurve 185144
""")

print(rtn)

returns

status= error
msg= Sorry, system appears to be busy.
None

and has done so for 203 hours. I don't quite understand what is happening. There is nothing in the docs I can find that explains what is happening and what to do under these circumstances, and how I can exit and restart. Is suspect this is a documentation issue?

**Comment by bjfultn** [comment]
It is possible to get into states where that busy file isn't removed properly and it disallows you to do much else. I think we got you unstuck and moving again and this should be uncommon once we work out the current bugs. I'll close this for now, but feel free to re-open if you are still stuck or get into this state again.
