### ISSUE TITLE
Missing link to notebook

### ISSUE THREAD

**Issue by GBruceB** [Caltech-IPAC/hiresprv#38]
In the advanced turorial, 

"You can download and interact with your own copy of this notebook here"

the link gives a 404 error.

**Comment by bjfultn** [comment]
The link seems to work for me. This is the URL https://caltech-ipac.github.io/hiresprv/_static/Advanced_Usage.ipynb. Maybe this is a GitHub permissions issue? Are you logged into your GitHub account (although I didn't think that would matter)?

**Comment by GBruceB** [comment]
Works now
