### ISSUE TITLE
Last step in Notebooks fails 

### ISSUE THREAD

**Issue by GBruceB** [Caltech-IPAC/hiresprv#41]
I got all the way through the notebooks this time, except for the very final step in both notebooks:

from hiresprv.download import Download

data = Download('prv.cookies')

rtn = data.rvcurve('185144')

with open('vst185144.csv', 'r') as file:
  for line in file:
    print(line, end='')

Traceback:
TypeError                                 Traceback (most recent call last)
<ipython-input-35-d2440708f2de> in <module>()
      1 from hiresprv.download import Download
      2 
----> 3 data = Download('prv.cookies')
      4 
      5 rtn = data.rvcurve('185144')

TypeError: __init__() missing 1 required positional argument: 'localdir'

**Comment by bjfultn** [comment]
Fixed in PR #42
