### ISSUE TITLE
Feature Request - hiresprv.ipac.caltech.edu landing page

### ISSUE THREAD

**Issue by maswain** [Caltech-IPAC/hiresprv#47]
Hi,

When I go to this page:  http://hiresprv.ipac.caltech.edu
It says "This is just a placeholder."

Maybe this page should have a short introduction/overview with links to the documentation or redirect to wherever new users might go (granted this is probably not a normal starting point, but it might be useful for new users.)

-Melanie

**Comment by bjfultn** [comment]
I'd be ok with simply re-directing to the documentation page. Does anyone know where this file is located?

**Comment by bjfultn** [comment]
Re-assigning to @JohnGood. Maybe he knows where this default HTML page is stored in the web server directories.
