### ISSUE TITLE
Better messaging/error trapping on bad dates

### ISSUE THREAD

**Issue by maswain** [Caltech-IPAC/hiresprv#48]
Hi,
If you enter a date with incorrect format  (say a  character string or without hyphens like the following:

rtn = koa.by_dates("""20091231
20130629
20130912
20150606
""")

The response is:
post request exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

Perhaps an error can be returned that the date is not in the correct format rather than Connection aborted.

-Melanie

**Comment by bjfultn** [comment]
Implemented a date checker in PR #50
