### ISSUE TITLE
'rvcurve' command failed.

### ISSUE THREAD

**Issue by lshuai310** [Caltech-IPAC/hiresprv#61]
Hello,
All the RV observations reduce successfully when I compute the rvcure of HD22233,  but the ERROR displayed of 'rvcurve' command failed, and just one sentence of "status":"Failed to open requested file vst22233.csv in your workspace." written in vst22233.csv. In addition, some other rv curves such as HD18645, vst18645.csv just export two lines, but rtn = idl.run_script() recorded 13 RV observations which reduced successfully. I could not figure out why these problems arisen, thanks a lot if you can interrupt that for me.
Thank you ,
Shuai, LIu
National Astronomical Observatories，Chinese Academy of Sciences.

**Comment by bjfultn** [comment]
You may have initialized your workspace during a time when we were in the midst of deploying some updates and bug fixes. Have you done a lot of work in your workspace that is important to save? Or would you be willing to to reset your workspace to the new default state (which includes all public PRV data from 2004-2018 already pre-processed and ready for download)?

**Comment by lshuai310** [comment]
Hello,
I am not sure whether I initialized my workspace when you were in the midst of deploying some updates and bug fixes. I am willing to reset my workspace to new default state (which includes all public PRV data from 2004-2018 already pre-processed and ready for download).
Thank you,
Shuai Liu

**Comment by bjfultn** [comment]
OK, your workspace has been reset. Please log in with your KOA credentials again to complete the initialization. Let me know if this fixes the issue.

**Comment by lshuai310** [comment]
Thank you!  This issue has been fixed.
